// AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const FETCH_USER_FROM_TOKEN_INIT = "FETCH_USER_FROM_TOKEN_INIT";
export const FETCH_USER_FROM_TOKEN_SUCCESS = "FETCH_USER_FROM_TOKEN_SUCCESS";
export const FETCH_USER_FROM_TOKEN_ERROR = "FETCH_USER_FROM_TOKEN_ERROR";

// PROJECT
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR";

export const FETCH_SINGLE_PROJECT_SUCCESS = "FETCH_SINGLE_PROJECT_SUCCESS";
export const FETCH_SINGLE_PROJECT_ERROR = "FETCH_SINGLE_PROJECT_ERROR";

export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_ERROR = "EDIT_PROJECT_ERROR";

// TASK
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

export const CHANGE_TASK_STATUS_SUCCESS = "CHANGE_TASK_STATUS_SUCCESS";
export const CHANGE_TASK_STATUS_ERROR = "CHANGE_TASK_STATUS_ERROR";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";

// TASKS
export const INIT_TASKS_SUCCESS = "INIT_TASKS_SUCCESS";
export const INIT_TASKS_ERROR = "INIT_TASKS_ERROR";

export const ADD_TASK_TO_SELECTED = "ADD_TASK_TO_SELECTED";
export const REMOVE_TASK_FROM_SELECTED = "REMOVE_TASK_FROM_SELECTED";

export const REMOVE_ALL_SELECTED_SUCCESS = "REMOVE_ALL_SELECTED_SUCCESS";
export const REMOVE_ALL_SELECTED_ERROR = "REMOVE_ALL_SELECTED_ERROR";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";
