export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const FETCH_USER_FROM_TOKEN_INIT = "FETCH_USER_FROM_TOKEN_INIT";
export const FETCH_USER_FROM_TOKEN_SUCCESS = "FETCH_USER_FROM_TOKEN_SUCCESS";
export const FETCH_USER_FROM_TOKEN_ERROR = "FETCH_USER_FROM_TOKEN_ERROR";

export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR";

export const FETCH_SINGLE_PROJECT_SUCCESS = "FETCH_SINGLE_PROJECT_SUCCESS";
export const FETCH_SINGLE_PROJECT_ERROR = "FETCH_SINGLE_PROJECT_ERROR";

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const COMPLETE_TASK_ERROR = "COMPLETE_TASK_ERROR";

export const ADD_TASK_TO_SELECTED = "ADD_TASK_TO_SELECTED";
export const REMOVE_TASK_FROM_SELECTED = "REMOVE_TASK_FROM_SELECTED";
