export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const FETCH_USER_FROM_TOKEN_INIT = "FETCH_USER_FROM_TOKEN_INIT";
export const FETCH_USER_FROM_TOKEN_SUCCESS = "FETCH_USER_FROM_TOKEN_SUCCESS";
export const FETCH_USER_FROM_TOKEN_ERROR = "FETCH_USER_FROM_TOKEN_ERROR";
